import { ButtonBuilder, EmbedBuilder, Snowflake } from 'discord.js';
import { HouseID, HousePoints } from './House/HousePointManager';
export declare function buildChangesMessage(before: HousePoints, after: HousePoints): string;
export declare const UserInfoButton: (user: Snowflake, label?: string) => ButtonBuilder;
export declare const UndoChangesButton: (changes: string, label?: string) => ButtonBuilder;
export declare const LeaderboardButton: (label?: string) => ButtonBuilder;
export declare const HouseInfoButton: (house: HouseID, label?: string) => ButtonBuilder;
export declare const RevokeBanButton: (user: Snowflake, label?: string) => ButtonBuilder;
export declare const BanButton: (user: Snowflake, label?: string) => ButtonBuilder;
export declare const LeaderboardEmbed: (sorted: [string, number][]) => EmbedBuilder;
